name: coffee_disease_app
description: "An advanced Flutter project for Coffee Leaf Disease Detection with JARC protocols."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  geolocator: ^13.0.1  # Maps your structural GPS coordinate hardware tags
  flutter_tts: ^4.1.0  # Powers your text to speech audio readout speaker loops

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

