name: Coffee Leaf Disease Offline APK Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11' # ከፍሉተር 3.7 ጋር ፍጹም የሚስማማው JDK 11 ነው

      - name: Set up Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0' # ካንተ የGradle ፋይሎች ጋር የሚስማማው ስሪት

      - name: Install dependencies
        run: flutter pub get

      - name: Build Split Multi-Architecture Release APKs
        run: flutter build apk --release --split-per-abi

      - name: Upload Generated APKs to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: coffee-leaf-release-apks
          path: build/app/outputs/flutter-apk/*-release.apk

